
package StudentResultSystem;

import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;



import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableColumn;

/**
 *
 * @author kbala
 */
public class StudentResultSystem extends javax.swing.JFrame {

    /**
     * Creates new form StudentResultSystem
     */
    String username = "root";
    String password = "123456";
    String dataCon = "jdbc:mysql://localhost:3306/resultdb?serverTimezone=America/New_York";
    
    Connection sqlCon = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
   
        
    int q,i;
    
    public StudentResultSystem() {
        
        initComponents();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void uploadDB(){
      
        try{
              Class.forName("com.mysql.jdbc.Driver");
              sqlCon = DriverManager.getConnection(dataCon,username,password);
              pst = sqlCon.prepareStatement("select * from resultdb");
              rs = pst.executeQuery();
              ResultSetMetaData stData = rs.getMetaData();
              
              q = stData.getColumnCount();
              
              DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
              RecordTable.setRowCount(0);
              while(rs.next()){
                  Vector columnDate = new Vector();
                  for(i=1;i<=q;i++){
                      columnDate.add(rs.getString("StudentID"));
                      columnDate.add(rs.getString("Firstname"));
                      columnDate.add(rs.getString("Surname"));
                      columnDate.add(rs.getString("Address"));
                      columnDate.add(rs.getString("Gender"));
                      
                      columnDate.add(rs.getString("DOB"));
                      columnDate.add(rs.getString("Mobile"));
                      columnDate.add(rs.getString("Course"));
                      columnDate.add(rs.getString("CourseCode"));
                      columnDate.add(rs.getString("Module1"));
                      columnDate.add(rs.getString("Module2"));
                      columnDate.add(rs.getString("Module3"));
                      columnDate.add(rs.getString("Module4"));
                      columnDate.add(rs.getString("Module5"));
                      columnDate.add(rs.getString("Module6"));
                      columnDate.add(rs.getString("Module7"));
                      columnDate.add(rs.getString("Module8"));
                      
                      columnDate.add(rs.getString("Score1"));
                      columnDate.add(rs.getString("Score2"));
                      columnDate.add(rs.getString("Score3"));
                      columnDate.add(rs.getString("Score4"));
                      columnDate.add(rs.getString("Score5"));
                      columnDate.add(rs.getString("Score6"));
                      columnDate.add(rs.getString("Score7"));
                      columnDate.add(rs.getString("Score8"));
                      
                      columnDate.add(rs.getString("TotalScore"));
                      columnDate.add(rs.getString("Ranking"));
                      columnDate.add(rs.getString("Date"));
                      
                      
                      
                  }
                  RecordTable.addRow(columnDate);
              }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, username);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jcboCourse = new javax.swing.JComboBox<>();
        jtxtCourseCode = new javax.swing.JTextField();
        jtxtFacultyName = new javax.swing.JTextField();
        jtxtDeanOfFaculty = new javax.swing.JTextField();
        jtxtProgramLeader = new javax.swing.JTextField();
        jtxtCourseTutor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtScore1 = new javax.swing.JTextField();
        jtxtTotalScore = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jtxtDate = new javax.swing.JTextField();
        txtScore2 = new javax.swing.JTextField();
        txtScore3 = new javax.swing.JTextField();
        txtScore4 = new javax.swing.JTextField();
        txtScore5 = new javax.swing.JTextField();
        txtScore6 = new javax.swing.JTextField();
        jcboModule1 = new javax.swing.JComboBox<>();
        txtScore7 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jcboModule2 = new javax.swing.JComboBox<>();
        jcboModule3 = new javax.swing.JComboBox<>();
        jcboModule4 = new javax.swing.JComboBox<>();
        jcboModule5 = new javax.swing.JComboBox<>();
        jcboModule6 = new javax.swing.JComboBox<>();
        jcboModule7 = new javax.swing.JComboBox<>();
        jcboModule8 = new javax.swing.JComboBox<>();
        txtScore8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcboGender = new javax.swing.JComboBox<>();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtSurname = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtDOB = new javax.swing.JTextField();
        jtxtMobile = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbtnPrint = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnResult = new javax.swing.JButton();
        jbtnTranscription = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Course Tutor");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Dean of Faculty");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Program Leader");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Facultu Name");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("Course");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("Course Code");

        jcboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Course", "BA Animation", "BSc Computing", "BSc Computer Science", "BSc Computer Animation", "BSc Serios Games", "BSc Information System", " ", " " }));
        jcboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCourseActionPerformed(evt);
            }
        });

        jtxtCourseCode.setPreferredSize(new java.awt.Dimension(120, 24));
        jtxtCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCourseCodeActionPerformed(evt);
            }
        });

        jtxtFacultyName.setPreferredSize(new java.awt.Dimension(120, 24));

        jtxtDeanOfFaculty.setPreferredSize(new java.awt.Dimension(120, 24));

        jtxtProgramLeader.setPreferredSize(new java.awt.Dimension(120, 24));

        jtxtCourseTutor.setPreferredSize(new java.awt.Dimension(120, 24));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtDeanOfFaculty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtFacultyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtCourseTutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtProgramLeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcboCourse, 0, 180, Short.MAX_VALUE)
                                    .addComponent(jtxtCourseCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtxtDeanOfFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtProgramLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jtxtCourseTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jtxtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jtxtFacultyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("No");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("1");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Date");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Ranking");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Total Score");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Unit Selector");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Score");

        txtScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore1.setText("0");
        txtScore1.setEnabled(false);
        txtScore1.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore1ActionPerformed(evt);
            }
        });

        jtxtTotalScore.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtRanking.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtDate.setPreferredSize(new java.awt.Dimension(120, 22));
        jtxtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDateActionPerformed(evt);
            }
        });

        txtScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore2.setText("0");
        txtScore2.setEnabled(false);
        txtScore2.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore2ActionPerformed(evt);
            }
        });

        txtScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore3.setText("0");
        txtScore3.setEnabled(false);
        txtScore3.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore3ActionPerformed(evt);
            }
        });

        txtScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore4.setText("0");
        txtScore4.setEnabled(false);
        txtScore4.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore4ActionPerformed(evt);
            }
        });

        txtScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore5.setText("0");
        txtScore5.setEnabled(false);
        txtScore5.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore5ActionPerformed(evt);
            }
        });

        txtScore6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore6.setText("0");
        txtScore6.setEnabled(false);
        txtScore6.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore6ActionPerformed(evt);
            }
        });

        jcboModule1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Visual C++Programming", "Visual C# Programming", "Phyton Programming" }));
        jcboModule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule1ActionPerformed(evt);
            }
        });

        txtScore7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore7.setText("0");
        txtScore7.setEnabled(false);
        txtScore7.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore7ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setText("2");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel29.setText("3");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel30.setText("4");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("5");
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel32.setText("6");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setText("7");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setText("8");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jcboModule2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SQL", "Database", "Spreadsheet", " " }));
        jcboModule2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule2ActionPerformed(evt);
            }
        });

        jcboModule3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "System Analysis", "Network Management", "Information Technology" }));
        jcboModule3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule3ActionPerformed(evt);
            }
        });

        jcboModule4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Statistics", "Data Scientice", "Machine Learning", "Artificial Intelligence", " " }));
        jcboModule4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule4ActionPerformed(evt);
            }
        });

        jcboModule5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "PHP Programming", "Computer game dev", "Web Site development" }));
        jcboModule5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule5ActionPerformed(evt);
            }
        });

        jcboModule6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Object Oriented Programming", "Software Testing", "Procedural Programming", " ", " " }));
        jcboModule6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule6ActionPerformed(evt);
            }
        });

        jcboModule7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Matplotib", "Raspberry Pi", "Cyber Security" }));
        jcboModule7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule7ActionPerformed(evt);
            }
        });

        jcboModule8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JavaScript", "Animation", "Graphic Design", "Digital Graphics" }));
        jcboModule8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboModule8ActionPerformed(evt);
            }
        });

        txtScore8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScore8.setText("0");
        txtScore8.setEnabled(false);
        txtScore8.setPreferredSize(new java.awt.Dimension(54, 22));
        txtScore8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScore8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtScore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtScore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(txtScore3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(txtScore5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(txtScore7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(txtScore4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboModule6, 0, 1, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(txtScore6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcboModule8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(txtScore8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtScore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboModule1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jcboModule2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScore3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(jcboModule3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtScore4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jcboModule4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtScore5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jcboModule5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScore6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jcboModule6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtScore7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jcboModule7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jcboModule8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtScore8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jtxtTotalScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Student ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Surname");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("DOB");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Mobile");

        jcboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Male", "Female" }));

        jtxtStudentID.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtFirstname.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtSurname.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtAddress.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtDOB.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtMobile.setPreferredSize(new java.awt.Dimension(120, 22));

        jtxtEmail.setPreferredSize(new java.awt.Dimension(120, 22));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnAdd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnAdd.setText("Add");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnResult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnResult.setText("Result");
        jbtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultActionPerformed(evt);
            }
        });

        jbtnTranscription.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnTranscription.setText("Transcript");
        jbtnTranscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptionActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTranscription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnResult)
                    .addComponent(jbtnAdd)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnTranscription))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("School Record", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setText("Student Result Management System");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Srudent ID", "Firstname", "Surname", "Address", "Gender", "DOB", "Mobile", "Email", "Course", "CourseCode", "Module1", "Module2", "Module3", "Module4", "Module5", "Module6", "Module7", "Module8", "Score1", "Score2", "Score3", "Score4", "Score5", "Score6", "Score7", "Score8", "TotalScore", "Ranking", "Date"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Student Record", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore1ActionPerformed

    private void txtScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore2ActionPerformed

    private void txtScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore3ActionPerformed

    private void txtScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore4ActionPerformed

    private void txtScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore5ActionPerformed

    private void txtScore6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore6ActionPerformed

    private void txtScore7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore7ActionPerformed

    private void txtScore8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScore8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScore8ActionPerformed

    private void jtxtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDateActionPerformed

    private void jcboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCourseActionPerformed
           if(jcboCourse.getSelectedItem().equals("BA Animation")){
               jtxtCourseCode.setText("BA08595"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Daniel Moorehouse");
               jtxtProgramLeader.setText("Dr. Kerry Casey");
               jtxtCourseTutor.setText("Dr. Tony Anthony");
      
               
           }
           else if(jcboCourse.getSelectedItem().equals("BSc Computing")){
               jtxtCourseCode.setText("BA08595"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Ivan Bistritskiy");
               jtxtProgramLeader.setText("Dr. Jim Hill");
               jtxtCourseTutor.setText("Dr. Kristian Rulo");
           }
           else if(jcboCourse.getSelectedItem().equals("BSc Computer Science")){
               jtxtCourseCode.setText("BA00085"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Bill Harington");
               jtxtProgramLeader.setText("Dr. Don Virsaty");
               jtxtCourseTutor.setText("Dr. Oleg Dobrov");
           }
           else if(jcboCourse.getSelectedItem().equals("BSc Computer Animation")){
               jtxtCourseCode.setText("BA01595"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Kirill Petrov");
               jtxtProgramLeader.setText("Dr. Sara Anthony");
               jtxtCourseTutor.setText("Dr. Richard Cherchel");
           }
           else if(jcboCourse.getSelectedItem().equals("BSc Serios Games")){
               jtxtCourseCode.setText("BA08544"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Li Jo");
               jtxtProgramLeader.setText("Dr. Mick Jager");
               jtxtCourseTutor.setText("Dr. Tony Anthony");
           }else if(jcboCourse.getSelectedItem().equals("BSc Information System")){
               jtxtCourseCode.setText("BA03335"); 
               jtxtFacultyName.setText("School of Art");
               jtxtDeanOfFaculty.setText("Prof. Daniel Moorehouse");
               jtxtProgramLeader.setText("Dr. Kerry Casey");
               jtxtCourseTutor.setText("Dr. Tony Anthony");
           }else if(jcboCourse.getSelectedItem().equals("Select a Course")){
               JTextField jtxt  = null;
           for(Component c:jPanel5.getComponents()){
               if(c.getClass().toString().contains("javax.swing.JTxtField")){
                   jtxt = (JTextField)c;
                   jtxt.setText(null);
               }
           }
           }
           
          
    }//GEN-LAST:event_jcboCourseActionPerformed

    private void jtxtCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCourseCodeActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
            try 
            {
                jtxtTranscript.print();
            }
            catch(java.awt.print.PrinterException e)
            {
                   System.err.format("No Printer found", e.getMessage());
            }
    }//GEN-LAST:event_jbtnPrintActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog( frame, "Confirm if you want to exit", "Student Result System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {{
            System.exit(0);
            
        }}
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
       JTextField jtxt = null;
       JComboBox jcbo = null;
       
       for(Component c:jPanel5.getComponents()){
           if(c.getClass().toString().contains("javax.swing.JTextField")){
               jtxt = (JTextField)c;
               jtxt.setText(null);
           }
       }
       for(Component c:jPanel4.getComponents()){
           if(c.getClass().toString().contains("javax.swing.JComboBox")){
               jcbo= (JComboBox)c;
               jcbo.setSelectedIndex(0);
           }
       }
        for(Component c:jPanel2.getComponents()){
           if(c.getClass().toString().contains("javax.swing.JTextField")){
               jtxt = (JTextField)c;
               jtxt.setText(null);
           }
       }
        jtxtTranscript.setText(null);
        jcboGender.setSelectedIndex(0);
        jcboCourse.setSelectedIndex(0);
        jtxtTotalScore.setText("");
        jtxtRanking.setText("");
        jtxtDate.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultActionPerformed
             int[] score = new int[9];
             
             score[0] = Integer.parseInt(txtScore1.getText()); 
             score[1] = Integer.parseInt(txtScore2.getText()); 
              score[2] = Integer.parseInt(txtScore3.getText()); 
               score[3] = Integer.parseInt(txtScore4.getText()); 
                score[4] = Integer.parseInt(txtScore5.getText()); 
                 score[5] = Integer.parseInt(txtScore6.getText()); 
                  score[6] = Integer.parseInt(txtScore7.getText()); 
                   score[7] = Integer.parseInt(txtScore8.getText()); 
                   
                    score[8] =  score[0]+score[1]+score[2]+score[3]+score[4]+score[5]+score[6]+score[7]; 
                    jtxtTotalScore.setText(Integer.toString(score[8]));
                    if(score[8]>=700){
                        jtxtRanking.setText("1st Class");
                    }else if (score[8]>=600){
                         jtxtRanking.setText("2i Class Upper");
                    }else if (score[8]>=500){
                         jtxtRanking.setText("2ii Class Lower");
                    }else if (score[8]>=400){
                         jtxtRanking.setText("3rd Class");
                    }else if (score[8]>=300){
                         jtxtRanking.setText("CoHE");
                    }else{
                         jtxtRanking.setText("Fail");
                    }
                    Calendar ToDay = Calendar.getInstance();
                    ToDay.getTime();
                    SimpleDateFormat Td = new SimpleDateFormat("dd-MMM-YYY");
                    jtxtDate.setText(Td.format(ToDay.getTime()));
                    if(score[0]>100){
                        txtScore1.setText("0");
                    }
                    if(score[1]>100){
                        txtScore2.setText("0");
                    }
                    if(score[2]>100){
                        txtScore3.setText("0");
                    }
                    if(score[3]>100){
                        txtScore4.setText("0");
                    }
                    if(score[4]>100){
                        txtScore5.setText("0");
                    }
                    if(score[5]>100){
                        txtScore6.setText("0");
                    }
                    if(score[6]>100){
                        txtScore7.setText("0");
                    }
                    if(score[7]>100){
                        txtScore8.setText("0");
                    }
    }//GEN-LAST:event_jbtnResultActionPerformed

    private void jbtnTranscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptionActionPerformed
        jtxtTranscript.append("\t\t Transcript \n"
                + "=============================\n"
                + "Student Registration Number: "+jtxtStudentID.getText()+"\n\n"
                + "Name: "+jtxtFirstname.getText()+"\n\n"
                + "Surname:  "+jtxtSurname.getText()+"\n\n"
                + "1:  "+jcboModule1.getSelectedItem()+" "+txtScore1.getText()+"\n\n"
                + "2:  "+jcboModule2.getSelectedItem()+" "+txtScore2.getText()+"\n\n"
                + "3:  "+jcboModule3.getSelectedItem()+" "+txtScore3.getText()+"\n\n"
                + "4:  "+jcboModule4.getSelectedItem()+" "+txtScore4.getText()+"\n\n"
                + "5:  "+jcboModule5.getSelectedItem()+" "+txtScore5.getText()+"\n\n"
                + "6:  "+jcboModule6.getSelectedItem()+" "+txtScore6.getText()+"\n\n"
                + "7:  "+jcboModule7.getSelectedItem()+" "+txtScore7.getText()+"\n\n"
                + "8:  "+jcboModule8.getSelectedItem()+" "+txtScore8.getText()+"\n\n"
                + "============================\n"
                + "Total Score: \t\t"+jtxtTotalScore.getText()+"\n"
                + "Ranking: \t\t"+jtxtTotalScore.getText()+"\n"
                + "Date: \t\t"+jtxtTotalScore.getText()+"\n");
    }//GEN-LAST:event_jbtnTranscriptionActionPerformed

    private void jcboModule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule1ActionPerformed
        if(jcboModule1.getSelectedItem().equals("")){
            txtScore1.setText("0");
            txtScore1.setEnabled(false);
            
        }else{
            txtScore1.setText("");
            txtScore1.setEnabled(true);
            txtScore1.requestFocus();
        }
        
    }//GEN-LAST:event_jcboModule1ActionPerformed

    private void jcboModule2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule2ActionPerformed

         if(jcboModule2.getSelectedItem().equals("")){
            txtScore2.setText("0");
            txtScore2.setEnabled(false);
            
        }else{
            txtScore2.setText("");
            txtScore2.setEnabled(true);
            txtScore2.requestFocus();
        }
    }//GEN-LAST:event_jcboModule2ActionPerformed

    private void jcboModule3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule3ActionPerformed
        if(jcboModule3.getSelectedItem().equals("")){
            txtScore3.setText("0");
            txtScore3.setEnabled(false);
            
        }else{
            txtScore3.setText("");
            txtScore3.setEnabled(true);
            txtScore3.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jcboModule3ActionPerformed

    private void jcboModule4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule4ActionPerformed
        if(jcboModule4.getSelectedItem().equals("")){
            txtScore4.setText("0");
            txtScore4.setEnabled(false);
            
        }else{
            txtScore4.setText("");
            txtScore4.setEnabled(true);
            txtScore4.requestFocus();
        }        
    }//GEN-LAST:event_jcboModule4ActionPerformed

    private void jcboModule5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule5ActionPerformed
        if(jcboModule5.getSelectedItem().equals("")){
            txtScore5.setText("0");
            txtScore5.setEnabled(false);
            
        }else{
            txtScore5.setText("");
            txtScore5.setEnabled(true);
            txtScore5.requestFocus();
        }        
    }//GEN-LAST:event_jcboModule5ActionPerformed

    private void jcboModule6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule6ActionPerformed
        if(jcboModule6.getSelectedItem().equals("")){
            txtScore6.setText("0");
            txtScore6.setEnabled(false);
            
        }else{
            txtScore6.setText("");
            txtScore6.setEnabled(true);
            txtScore6.requestFocus();
        }       
    }//GEN-LAST:event_jcboModule6ActionPerformed

    private void jcboModule7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule7ActionPerformed
        if(jcboModule7.getSelectedItem().equals("")){
            txtScore7.setText("0");
            txtScore7.setEnabled(false);
            
        }else{
            txtScore7.setText("");
            txtScore7.setEnabled(true);
            txtScore7.requestFocus();
        }       
    }//GEN-LAST:event_jcboModule7ActionPerformed

    private void jcboModule8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboModule8ActionPerformed
        if(jcboModule8.getSelectedItem().equals("")){
            txtScore8.setText("0");
            txtScore8.setEnabled(false);
            
        }else{
            txtScore8.setText("");
            txtScore8.setEnabled(true);
            txtScore8.requestFocus();
        }        
    }//GEN-LAST:event_jcboModule8ActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try{
           Class.forName("com.mysql.jdbc.Driver");
            sqlCon = DriverManager.getConnection(dataCon,username,password);
            pst = sqlCon.prepareStatement("INSERT INTO resultdb(StudentID, Firstname, Surname, Address, Gender,"
                    + "DOB, Mobile,Email,Course,CourseCode,"
                    + "Module1,Module2,Module3,Module4,Module5,Module6,Module7,Module8,"
                    + "Score1,Score2,Score3,Score4,Score5,Score6,Score7,Score8,"
                    + "TotalScore,Ranking,Date)"
                    + "value(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); 
                        /*    +jtxtStudentID.getText()+","+jtxtFirstname.getText()+","
                            +jtxtSurname.getText()+","+jtxtAddress.getText() +","
                            +(String) jcboGender.getSelectedItem()+","+jtxtDOB.getText()+ ","
                            + jtxtMobile.getText()+","+jtxtEmail.getText()+","
                            + (String) jcboCourse.getSelectedItem()+","+jtxtCourseCode.getText()+","
                            + (String) jcboModule1.getSelectedItem()+","+(String) jcboModule2.getSelectedItem()+","
                            + (String) jcboModule3.getSelectedItem()+","+(String) jcboModule4.getSelectedItem()+","
                            + (String) jcboModule5.getSelectedItem()+","+(String) jcboModule6.getSelectedItem()+","
                            + (String) jcboModule7.getSelectedItem()+","+(String) jcboModule8.getSelectedItem()+","
                            + (String) txtScore1.getText()+","+(String) txtScore2.getText()+","
                            + (String) txtScore3.getText()+","+(String) txtScore4.getText()+","
                            + (String) txtScore5.getText()+","+(String) txtScore6.getText()+","
                            + (String) txtScore7.getText()+","+(String) txtScore8.getText()+","
                            + (String) jtxtTotalScore.getText()+","+jtxtRanking.getText()+","
                            + jtxtDate.getText()*/
                  
            pst.setString(1,jtxtStudentID.getText());
            pst.setString(2,jtxtFirstname.getText());
            pst.setString(3,jtxtSurname.getText());
            pst.setString(4,jtxtAddress.getText());
            pst.setString(5,(String) jcboGender.getSelectedItem());
            pst.setString(6,jtxtDOB.getText());
            pst.setString(7,jtxtMobile.getText());
            pst.setString(8,jtxtEmail.getText());
            pst.setString(9,(String) jcboCourse.getSelectedItem());
            pst.setString(10,jtxtCourseCode.getText());
           
            pst.setString(11,(String) jcboModule1.getSelectedItem());
            pst.setString(12,(String) jcboModule2.getSelectedItem());
            pst.setString(13,(String) jcboModule3.getSelectedItem());
            pst.setString(14,(String) jcboModule4.getSelectedItem());
            pst.setString(15,(String) jcboModule5.getSelectedItem());
            pst.setString(16,(String) jcboModule6.getSelectedItem());
            pst.setString(17,(String) jcboModule7.getSelectedItem());
            pst.setString(18,(String) jcboModule8.getSelectedItem());
            
            pst.setString(19,(String) txtScore1.getText());
            pst.setString(20,(String) txtScore2.getText());
            pst.setString(21,(String) txtScore3.getText());
            pst.setString(22,(String) txtScore4.getText());
            pst.setString(23,(String) txtScore5.getText());
            pst.setString(24,(String) txtScore6.getText());
            pst.setString(25,(String) txtScore7.getText());
            pst.setString(26,(String) txtScore8.getText());
            
            pst.setString(27,(String) jtxtTotalScore.getText());
            pst.setString(28,(String) jtxtRanking.getText());
            pst.setString(29,(String) jtxtDate.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student Result Updated");
            uploadDB();
            
            
        }catch(ClassNotFoundException ex){
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log
                    (java.util.logging.Level.SEVERE,null,ex);
        }catch(SQLException ex){
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log
                    (java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResultSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResultSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnResult;
    private javax.swing.JButton jbtnTranscription;
    private javax.swing.JComboBox<String> jcboCourse;
    private javax.swing.JComboBox<String> jcboGender;
    private javax.swing.JComboBox<String> jcboModule1;
    private javax.swing.JComboBox<String> jcboModule2;
    private javax.swing.JComboBox<String> jcboModule3;
    private javax.swing.JComboBox<String> jcboModule4;
    private javax.swing.JComboBox<String> jcboModule5;
    private javax.swing.JComboBox<String> jcboModule6;
    private javax.swing.JComboBox<String> jcboModule7;
    private javax.swing.JComboBox<String> jcboModule8;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCourseCode;
    private javax.swing.JTextField jtxtCourseTutor;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtDate;
    private javax.swing.JTextField jtxtDeanOfFaculty;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFacultyName;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtMobile;
    private javax.swing.JTextField jtxtProgramLeader;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextArea jtxtTranscript;
    private javax.swing.JTextField txtScore1;
    private javax.swing.JTextField txtScore2;
    private javax.swing.JTextField txtScore3;
    private javax.swing.JTextField txtScore4;
    private javax.swing.JTextField txtScore5;
    private javax.swing.JTextField txtScore6;
    private javax.swing.JTextField txtScore7;
    private javax.swing.JTextField txtScore8;
    // End of variables declaration//GEN-END:variables
}
